theme: jekyll-theme-slate
title: Christophe Boutter
subtitle: 
author: Christophe Boutter
simple_search: http://google.com/search
description: I'm a german agilist, doing Java and dreaming about Ruby.
email: boutta@gmail.com

name: Christophe Boutter